code_examples/ch30/SessionTracking/src/java/sessiontracking/SelectionsBean.java
// SelectionsBean.java
// Manages a user's topic selections
package sessiontracking;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Set;
import java.util.TreeSet;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name="selectionsBean")
@SessionScoped
public class SelectionsBean implements Serializable
{
   // map of topics to book titles
   private static final HashMap< String, String > booksMap =
      new HashMap< String, String >();

   // initialize booksMap
   static 
   {
      booksMap.put("java", "Java How to Program");
      booksMap.put("cpp", "C++ How to Program");
      booksMap.put("iphone",
         "iPhone for Programmers: An App-Driven Approach");
      booksMap.put("android",
         "Android for Programmers: An App-Driven Approach");
   } 

   // stores individual user's selections
   private Set< String > selections = new TreeSet< String >();
   private String selection; // stores the current selection
   
   // return number of selections
   public int getNumberOfSelections()
   {
      return selections.size();
   } 

   // returns the current selection
   public String getSelection()
   {
      return selection;
   }

   // store user's selection
   public void setSelection(String topic)
   {
      selection = booksMap.get(topic);
      selections.add(selection);
   }

   // return the Set of selections
   public String[] getSelections()
   {
      return selections.toArray(new String[selections.size()]);
   } 
} 

/*************************************************************************
 * (C) Copyright 1992-2014 by Deitel & Associates, Inc. and              *
 * Pearson Education, Inc. All Rights Reserved.                          *
 *                                                                       *
 * DISCLAIMER: The authors and publisher of this book have used their    *
 * best efforts in preparing the book. These efforts include the         *
 * development, research, and testing of the theories and programs       *
 * to determine their effectiveness. The authors and publisher make      *
 * no warranty of any kind, expressed or implied, with regard to these   *
 * programs or to the documentation contained in these books. The authors*
 * and publisher shall not be liable in any event for incidental or      *
 * consequential damages in connection with, or arising out of, the      *
 * furnishing, performance, or use of these programs.                    *
 ************************************************************************/

code_examples/ch30/SessionTracking/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>

<!-- index.xhtml -->
<!-- Allow the user to select a topic -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
   xmlns:h="http://java.sun.com/jsf/html"
   xmlns:f="http://java.sun.com/jsf/core">
   <h:head>
      <title>Topic Selection Page</title>
   </h:head>
   <h:body>
      <h1>Welcome to Sessions!</h1>
      <p>You have made #{selectionsBean.numberOfSelections} selection(s)
      </p>
      <h3>Make a Selection and Press Submit</h3>
      <h:form>
         <h:selectOneRadio id="topicSelectOneRadio" required="true"
            requiredMessage="Please choose a topic, then press Submit"
            value="#{selectionsBean.selection}">
            <f:selectItem itemValue="java" itemLabel="Java"/>
            <f:selectItem itemValue="cpp" itemLabel="C++"/>
            <f:selectItem itemValue="iphone" itemLabel="iPhone"/>
            <f:selectItem itemValue="android" itemLabel="Android"/>
         </h:selectOneRadio>
         <p><h:commandButton value="Submit"/></p>
      </h:form>
      <p><h:outputLink value="recommendations.xhtml">
         Click here for book recommendations
      </h:outputLink></p>
   </h:body>
</html>

<!--
**********************************************************************
* (C) Copyright 1992-2014 by Deitel & Associates, Inc. and           *
* Pearson Education, Inc. All Rights Reserved.                       *
*                                                                    *
* DISCLAIMER: The authors and publisher of this book have used their *
* best efforts in preparing the book. These efforts include the      *
* development, research, and testing of the theories and programs    *
* to determine their effectiveness. The authors and publisher make   *
* no warranty of any kind, expressed or implied, with regard to      *
* these programs or to the documentation contained in these books.   *
* The authors and publisher shall not be liable in any event for     *
* incidental or consequential damages in connection with, or         *
* arising out of, the furnishing, performance, or use of these       *
* programs.                                                          *
**********************************************************************
-->

code_examples/ch30/SessionTracking/web/recommendations.xhtml
<?xml version='1.0' encoding='UTF-8' ?>

<!-- recommendations.xhtml -->
<!-- Display recommended books based on the user's selected topics -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
   xmlns:h="http://java.sun.com/jsf/html"
   xmlns:ui="http://java.sun.com/jsf/facelets">
   <h:head>
      <title>Recommended Books</title>
   </h:head>
   <h:body>
      <h1>Book Recommendations</h1>
      <ul>
         <ui:repeat value="#{selectionsBean.selections}" var="book">
            <li>#{book}</li>
         </ui:repeat>
      </ul>
      <p><h:outputLink value="index.xhtml">
            Click here to choose another topic
         </h:outputLink></p>
   </h:body>
</html>



<!--
**********************************************************************
* (C) Copyright 1992-2014 by Deitel & Associates, Inc. and           *
* Pearson Education, Inc. All Rights Reserved.                       *
*                                                                    *
* DISCLAIMER: The authors and publisher of this book have used their *
* best efforts in preparing the book. These efforts include the      *
* development, research, and testing of the theories and programs    *
* to determine their effectiveness. The authors and publisher make   *
* no warranty of any kind, expressed or implied, with regard to      *
* these programs or to the documentation contained in these books.   *
* The authors and publisher shall not be liable in any event for     *
* incidental or consequential damages in connection with, or         *
* arising out of, the furnishing, performance, or use of these       *
* programs.                                                          *
**********************************************************************
-->